//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grant()
        {
            this.VKR_ThemesStudentOrder = new HashSet<VKR_ThemesStudentOrder>();
        }
    
        public int Id { get; set; }
        public string RegNumber { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public int Year { get; set; }
        public Nullable<int> YearFinish { get; set; }
        public Nullable<int> OrganizationId { get; set; }
    
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder { get; set; }
    }
}
