//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObrazProgramInYear
    {
        public System.Guid ObrazProgramInYearId { get; set; }
        public int ObrazProgramId { get; set; }
        public string Year { get; set; }
        public int LicenseProgramId { get; set; }
        public Nullable<int> SecondLicenseProgramId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public string StudyLevelName { get; set; }
        public int FacultyId { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual LicenseProgram LicenseProgram { get; set; }
        public virtual ObrazProgram ObrazProgram { get; set; }
    }
}
