//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationDogovorObrazProgram
    {
        public int Id { get; set; }
        public int DogovorId { get; set; }
        public bool AllPrograms { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public Nullable<int> ObrazProgramId { get; set; }
        public string Author { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual OrganizationDogovor OrganizationDogovor { get; set; }
    }
}
