//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployerPartnersEntities : DbContext
    {
        public EmployerPartnersEntities()
            : base("name=EmployerPartnersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_AppSettings> C_AppSettings { get; set; }
        public virtual DbSet<C_AppUsersSettings> C_AppUsersSettings { get; set; }
        public virtual DbSet<C_AppUsersVersion> C_AppUsersVersion { get; set; }
        public virtual DbSet<C_Settings> C_Settings { get; set; }
        public virtual DbSet<ActivityArea> ActivityAreas { get; set; }
        public virtual DbSet<ActivityAreaProfessional> ActivityAreaProfessionals { get; set; }
        public virtual DbSet<ActivityGoal> ActivityGoals { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<EPLog> EPLogs { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FileStorage> FileStorages { get; set; }
        public virtual DbSet<GAK_Adapter> GAK_Adapter { get; set; }
        public virtual DbSet<GAK_Address> GAK_Address { get; set; }
        public virtual DbSet<GAK_ChairmanSource> GAK_ChairmanSource { get; set; }
        public virtual DbSet<GAK_ExamVKR> GAK_ExamVKR { get; set; }
        public virtual DbSet<GAK_LP_Person> GAK_LP_Person { get; set; }
        public virtual DbSet<GAK_MemberNPR> GAK_MemberNPR { get; set; }
        public virtual DbSet<GAK_MemberNPR_archive> GAK_MemberNPR_archive { get; set; }
        public virtual DbSet<GAK_MemberNPR_log> GAK_MemberNPR_log { get; set; }
        public virtual DbSet<GAK_MemberPP> GAK_MemberPP { get; set; }
        public virtual DbSet<GAK_MemberPP_archive> GAK_MemberPP_archive { get; set; }
        public virtual DbSet<GAK_MemberPP_log> GAK_MemberPP_log { get; set; }
        public virtual DbSet<GAK_Number> GAK_Number { get; set; }
        public virtual DbSet<GAK_Number_archive> GAK_Number_archive { get; set; }
        public virtual DbSet<GAK_Number_log> GAK_Number_log { get; set; }
        public virtual DbSet<Grant> Grants { get; set; }
        public virtual DbSet<HelpFile> HelpFiles { get; set; }
        public virtual DbSet<License> Licenses { get; set; }
        public virtual DbSet<LicenseProgram> LicensePrograms { get; set; }
        public virtual DbSet<NationalAffiliation> NationalAffiliations { get; set; }
        public virtual DbSet<ObrazProgram> ObrazPrograms { get; set; }
        public virtual DbSet<ObrazProgramCharacteristic> ObrazProgramCharacteristics { get; set; }
        public virtual DbSet<ObrazProgramInYear> ObrazProgramInYears { get; set; }
        public virtual DbSet<OkvedType> OkvedTypes { get; set; }
        public virtual DbSet<OrgAddress> OrgAddresses { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OrganizationActivityArea> OrganizationActivityAreas { get; set; }
        public virtual DbSet<OrganizationActivityAreaProfessional> OrganizationActivityAreaProfessionals { get; set; }
        public virtual DbSet<OrganizationContact> OrganizationContacts { get; set; }
        public virtual DbSet<OrganizationDogovor> OrganizationDogovors { get; set; }
        public virtual DbSet<OrganizationDogovorFile> OrganizationDogovorFiles { get; set; }
        public virtual DbSet<OrganizationDogovorObrazProgram> OrganizationDogovorObrazPrograms { get; set; }
        public virtual DbSet<OrganizationEnglishSource> OrganizationEnglishSources { get; set; }
        public virtual DbSet<OrganizationMail> OrganizationMails { get; set; }
        public virtual DbSet<OrganizationName> OrganizationNames { get; set; }
        public virtual DbSet<OrganizationOkved> OrganizationOkveds { get; set; }
        public virtual DbSet<OrganizationPerson> OrganizationPersons { get; set; }
        public virtual DbSet<OrganizationRubric> OrganizationRubrics { get; set; }
        public virtual DbSet<OrganizationSubdivision> OrganizationSubdivisions { get; set; }
        public virtual DbSet<OwnershipType> OwnershipTypes { get; set; }
        public virtual DbSet<PartnerPerson> PartnerPersons { get; set; }
        public virtual DbSet<PartnerPersonActivityArea> PartnerPersonActivityAreas { get; set; }
        public virtual DbSet<PartnerPersonOrganizationLetter> PartnerPersonOrganizationLetters { get; set; }
        public virtual DbSet<PartnerPersonOrganizationNotAvailableInGAK> PartnerPersonOrganizationNotAvailableInGAKs { get; set; }
        public virtual DbSet<PartnerPersonOrganizationNotAvailableInGAK_Log> PartnerPersonOrganizationNotAvailableInGAK_Log { get; set; }
        public virtual DbSet<PartnerPersonPrefix> PartnerPersonPrefixes { get; set; }
        public virtual DbSet<PartnerPersonRubric> PartnerPersonRubrics { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Practice> Practices { get; set; }
        public virtual DbSet<PracticeOrganizationRoute> PracticeOrganizationRoutes { get; set; }
        public virtual DbSet<PracticeStudentOrganizationRoute> PracticeStudentOrganizationRoutes { get; set; }
        public virtual DbSet<PracticeStudent> PracticeStudents { get; set; }
        public virtual DbSet<ProgramType> ProgramTypes { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<Rank> Ranks { get; set; }
        public virtual DbSet<RankHonorary_> RankHonorary_ { get; set; }
        public virtual DbSet<RankState> RankStates { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RoutePlace> RoutePlaces { get; set; }
        public virtual DbSet<Rubric> Rubrics { get; set; }
        public virtual DbSet<SAP_ALL_PERS> SAP_ALL_PERS { get; set; }
        public virtual DbSet<SAP_ALL_PERS_SKUD> SAP_ALL_PERS_SKUD { get; set; }
        public virtual DbSet<SAP_GROUPS> SAP_GROUPS { get; set; }
        public virtual DbSet<SAP_NPR_Visible> SAP_NPR_Visible { get; set; }
        public virtual DbSet<SAP_ORGSTRUCTURE> SAP_ORGSTRUCTURE { get; set; }
        public virtual DbSet<SAP_ORGSTRUCTURE_SKUD> SAP_ORGSTRUCTURE_SKUD { get; set; }
        public virtual DbSet<SAP_POSITIONS> SAP_POSITIONS { get; set; }
        public virtual DbSet<SAP_POSITIONS_SKUD> SAP_POSITIONS_SKUD { get; set; }
        public virtual DbSet<SOP> SOPs { get; set; }
        public virtual DbSet<SOP_Conference> SOP_Conference { get; set; }
        public virtual DbSet<SOP_Conference_CommonQuestions> SOP_Conference_CommonQuestions { get; set; }
        public virtual DbSet<SOP_Conference_Questions> SOP_Conference_Questions { get; set; }
        public virtual DbSet<SOP_Conference_Questions_Files> SOP_Conference_Questions_Files { get; set; }
        public virtual DbSet<SOP_Conference_Questions_Results> SOP_Conference_Questions_Results { get; set; }
        public virtual DbSet<SOP_Conference_Questions_Speeches> SOP_Conference_Questions_Speeches { get; set; }
        public virtual DbSet<SOP_ConferenceMembers> SOP_ConferenceMembers { get; set; }
        public virtual DbSet<SOP_Members> SOP_Members { get; set; }
        public virtual DbSet<SOP_ObrazProgram> SOP_ObrazProgram { get; set; }
        public virtual DbSet<SOP_Orders> SOP_Orders { get; set; }
        public virtual DbSet<SOP_OrganizationMail> SOP_OrganizationMail { get; set; }
        public virtual DbSet<SOP_OrganizationMail_Files> SOP_OrganizationMail_Files { get; set; }
        public virtual DbSet<SOP_Position> SOP_Position { get; set; }
        public virtual DbSet<SP_AggregateGroup> SP_AggregateGroup { get; set; }
        public virtual DbSet<StudentFromSC> StudentFromSCs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudyLevel> StudyLevels { get; set; }
        public virtual DbSet<StudyPlanData> StudyPlanDatas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<VKR_OrderSource> VKR_OrderSource { get; set; }
        public virtual DbSet<VKR_Themes> VKR_Themes { get; set; }
        public virtual DbSet<VKR_Themes_NPR> VKR_Themes_NPR { get; set; }
        public virtual DbSet<VKR_Themes_OrderNums> VKR_Themes_OrderNums { get; set; }
        public virtual DbSet<VKR_Themes_Source> VKR_Themes_Source { get; set; }
        public virtual DbSet<VKR_Themes_StudyPlans> VKR_Themes_StudyPlans { get; set; }
        public virtual DbSet<VKR_ThemesStudent_Log> VKR_ThemesStudent_Log { get; set; }
        public virtual DbSet<VKR_ThemesStudentCustom> VKR_ThemesStudentCustom { get; set; }
        public virtual DbSet<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder { get; set; }
        public virtual DbSet<VKR_ThemesStudentOrder_Log> VKR_ThemesStudentOrder_Log { get; set; }
        public virtual DbSet<VKR_ThemesStudentOrder_NR_Review> VKR_ThemesStudentOrder_NR_Review { get; set; }
        public virtual DbSet<VKR_ThemesStudentSelected> VKR_ThemesStudentSelected { get; set; }
        public virtual DbSet<RolesMember> RolesMembers { get; set; }
    }
}
