//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerPersonOrganizationNotAvailableInGAK
    {
        public int Id { get; set; }
        public Nullable<int> PartnerPersonId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
