//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Practice()
        {
            this.PracticeOrganizationRoutes = new HashSet<PracticeOrganizationRoute>();
            this.PracticeStudents = new HashSet<PracticeStudent>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid StudyPlanId { get; set; }
        public int DisciplineId { get; set; }
        public string DisciplineNumber { get; set; }
        public string DisciplineName { get; set; }
        public int ModuleNameId { get; set; }
        public string ModuleName { get; set; }
        public int EducYear { get; set; }
        public int TrajectoryId { get; set; }
        public string TrajectoryName { get; set; }
        public int RealizationVariantId { get; set; }
        public string RealizationVariantName { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public string ProfileName { get; set; }
        public int StudyCourse { get; set; }
        public int StudyLevelId { get; set; }
        public int FacultyId { get; set; }
        public int LicenseProgramId { get; set; }
        public int ObrazProgramId { get; set; }
        public int ordId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeOrganizationRoute> PracticeOrganizationRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeStudent> PracticeStudents { get; set; }
    }
}
