//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesMember
    {
        public string FIO { get; set; }
        public bool BaseRoles { get; set; }
        public bool OrgRead { get; set; }
        public bool OrdWrite { get; set; }
        public bool GAKRead { get; set; }
        public bool GAKWrite { get; set; }
        public bool VKRRead { get; set; }
        public bool VKRWrite { get; set; }
        public bool PracticeRead { get; set; }
        public bool PracticeWrite { get; set; }
        public bool SOPRead { get; set; }
        public bool SOPWrite { get; set; }
        public bool SuperUser { get; set; }
        public bool LetterCreator { get; set; }
        public bool StudentUpdate { get; set; }
        public bool NPRUpdate { get; set; }
    }
}
