//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_ALL_PERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAP_ALL_PERS()
        {
            this.SOP_Members = new HashSet<SOP_Members>();
            this.VKR_ThemesStudentOrder_NR_Review = new HashSet<VKR_ThemesStudentOrder_NR_Review>();
        }
    
        public System.Guid Id { get; set; }
        public string Persnum { get; set; }
        public string Tabnum { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Birthdate { get; set; }
        public string Positionname { get; set; }
        public string OrgId { get; set; }
        public string OrgUpId { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string UsridAd { get; set; }
        public string Pkateg { get; set; }
        public string Pgroup { get; set; }
        public string Telnr { get; set; }
        public string Addressfact { get; set; }
        public string Titel { get; set; }
        public string Titl2 { get; set; }
        public string Civil { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public bool IsActive { get; set; }
    
        public virtual SAP_NPR_Visible SAP_NPR_Visible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOP_Members> SOP_Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder_NR_Review> VKR_ThemesStudentOrder_NR_Review { get; set; }
    }
}
