//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOP_ConferenceMembers
    {
        public int Id { get; set; }
        public int SOPConferenceId { get; set; }
        public bool Invitation { get; set; }
        public Nullable<System.Guid> SAPId { get; set; }
        public Nullable<int> PartnerPersonId { get; set; }
        public bool IsRemotely { get; set; }
        public bool IsAbsent { get; set; }
        public string Author { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual SOP_Conference SOP_Conference { get; set; }
    }
}
