//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.PracticeStudents = new HashSet<PracticeStudent>();
            this.VKR_ThemesStudentOrder = new HashSet<VKR_ThemesStudentOrder>();
        }
    
        public System.Guid StudentOid { get; set; }
        public Nullable<int> StudDataId { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SurnameEng { get; set; }
        public string FirstNameEng { get; set; }
        public string LastNameEng { get; set; }
        public string FIO_old { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<System.Guid> StudyPlanId { get; set; }
        public string StudyPlanNumber { get; set; }
        public string StudyForm { get; set; }
        public string StudyBasis { get; set; }
        public string FacultyName { get; set; }
        public string Status { get; set; }
        public string StudyingName { get; set; }
        public string EnterRuleName { get; set; }
        public Nullable<int> AggregateGroupId { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public Nullable<int> ObrazProgramId { get; set; }
        public Nullable<int> StudyLevelId { get; set; }
        public Nullable<int> StudyProfileId { get; set; }
        public string StudyProfileName { get; set; }
        public string PersonCountry { get; set; }
        public bool isActual { get; set; }
    
        public virtual LicenseProgram LicenseProgram { get; set; }
        public virtual ObrazProgram ObrazProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeStudent> PracticeStudents { get; set; }
        public virtual StudyLevel StudyLevel { get; set; }
        public virtual StudyPlanData StudyPlanData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder { get; set; }
    }
}
