//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFromSC
    {
        public System.Guid StudentOid { get; set; }
        public Nullable<int> StudDataId { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SurnameEng { get; set; }
        public string FirstNameEng { get; set; }
        public string LastNameEng { get; set; }
        public string PersonCountry { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> Course { get; set; }
        public string StudyPlanNumber { get; set; }
        public Nullable<int> StudyProfileId { get; set; }
        public string StudyProfileName { get; set; }
        public string StudyForm { get; set; }
        public string StudyBasis { get; set; }
        public string FacultyName { get; set; }
        public string Status { get; set; }
        public string StudyingName { get; set; }
        public string EnterRuleName { get; set; }
        public Nullable<bool> isActual { get; set; }
    }
}
