//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_Themes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VKR_Themes()
        {
            this.VKR_Themes_NPR = new HashSet<VKR_Themes_NPR>();
            this.VKR_Themes_OrderNums = new HashSet<VKR_Themes_OrderNums>();
            this.VKR_Themes_StudyPlans = new HashSet<VKR_Themes_StudyPlans>();
        }
    
        public int Id { get; set; }
        public int GraduateYear { get; set; }
        public string DocumentNumber { get; set; }
        public string VKRName { get; set; }
        public string VKRNameEng { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<int> ConsultPersonId { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string RKNum { get; set; }
        public Nullable<System.DateTime> RKDate { get; set; }
        public bool CommandWork { get; set; }
        public bool CanBeSelectedNextYear { get; set; }
        public bool EngOriginal { get; set; }
        public bool RecievedFromGAKMember { get; set; }
        public Nullable<int> PartnerPersonId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> EmailDate { get; set; }
        public bool HasGrant { get; set; }
        public string GrantInfo { get; set; }
        public Nullable<bool> ThesisDefencePassed { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual PartnerPerson PartnerPerson { get; set; }
        public virtual PartnerPerson PartnerPerson1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_Themes_NPR> VKR_Themes_NPR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_Themes_OrderNums> VKR_Themes_OrderNums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_Themes_StudyPlans> VKR_Themes_StudyPlans { get; set; }
    }
}
