//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_ThemesStudentOrder_NR_Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VKR_ThemesStudentOrder_NR_Review()
        {
            this.VKR_ThemesStudentOrder = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder1 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder2 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder3 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder4 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder5 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder6 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder7 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder8 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder9 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder10 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder11 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder12 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder13 = new HashSet<VKR_ThemesStudentOrder>();
            this.VKR_ThemesStudentOrder14 = new HashSet<VKR_ThemesStudentOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> SapId { get; set; }
        public Nullable<int> PartnerPersonId { get; set; }
        public string FIO { get; set; }
        public string Degree { get; set; }
        public string Rank { get; set; }
        public string Chair { get; set; }
        public string Account { get; set; }
        public string Faculty { get; set; }
        public string Position { get; set; }
    
        public virtual PartnerPerson PartnerPerson { get; set; }
        public virtual SAP_ALL_PERS SAP_ALL_PERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentOrder> VKR_ThemesStudentOrder14 { get; set; }
    }
}
