//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_Themes_NPR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VKR_Themes_NPR()
        {
            this.VKR_ThemesStudentSelected = new HashSet<VKR_ThemesStudentSelected>();
        }
    
        public int Id { get; set; }
        public int VKRThemeId { get; set; }
        public Nullable<System.Guid> SapId { get; set; }
        public string Tabnum { get; set; }
        public string NPR_Surname { get; set; }
        public string NPR_Name { get; set; }
        public string NPR_SecondName { get; set; }
        public string NPR_Position { get; set; }
        public string NPR_Degree { get; set; }
        public string NPR_Rank { get; set; }
        public string NPR_Account { get; set; }
        public string NPR_Chair { get; set; }
    
        public virtual VKR_Themes VKR_Themes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentSelected> VKR_ThemesStudentSelected { get; set; }
    }
}
