//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_ThemesStudent_Log
    {
        public int Id { get; set; }
        public Nullable<int> SelectedId { get; set; }
        public Nullable<System.Guid> StudentOid { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> VKRThemeNPRId { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> ThemeCustomId { get; set; }
        public string ThemeName { get; set; }
        public Nullable<System.Guid> SapId { get; set; }
        public string ActionName { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public Nullable<bool> FromLK { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> NewId { get; set; }
    }
}
