//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_ThemesStudentCustom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VKR_ThemesStudentCustom()
        {
            this.VKR_ThemesStudentSelected = new HashSet<VKR_ThemesStudentSelected>();
        }
    
        public int Id { get; set; }
        public string ThemeName { get; set; }
        public System.Guid SapId { get; set; }
        public Nullable<bool> IsConformed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_ThemesStudentSelected> VKR_ThemesStudentSelected { get; set; }
    }
}
